### ISSUE TITLE
GPU OOM during multi-gpu training

### ISSUE THREAD

**Issue by ChengshuLi** [fizyr/keras-retinanet#301]
Hi,

Thank you for your great work. 

I tried training on my own dataset using 4 GPUs with batch size 16 (so if I understand correctly, that's 4 images per GPU, right?). 

The training went okay for the first ~100 steps. Specifically, on each GPU I have ~12GB of memory and by running `nvidia-smi` I saw ~9 GB were used. So far so good. After 20 minutes, however, my GPUs ran out of memory. 

Before, I was able to train on 2 GPUs with batch size 8 (also 4 images per GPU), and there were no issues. I just want to utilize more GPUs and have larger batch size. 

tensorflow version: 1.4.1
keras version: 2.1.3

Any help would be greatly appreciated. Thanks! 

``` 
 File "keras_retinanet/bin/train.py", line 89, in create_models
    optimizer=optimizer
  File "/home/ecli/.local/lib/python2.7/site-packages/keras/engine/training.py", line 827, in compile
    sample_weight, mask)
  File "/home/ecli/.local/lib/python2.7/site-packages/keras/engine/training.py", line 426, in weighted
    score_array = fn(y_true, y_pred)
  File "keras_retinanet/bin/../../keras_retinanet/losses.py", line 45, in _focal
    cls_loss = focal_weight * keras.backend.binary_crossentropy(labels, classification)
  File "/home/ecli/.local/lib/python2.7/site-packages/keras/backend/tensorflow_backend.py", line 3069, in binary_crossentropy
    logits=output)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/nn_impl.py", line 169, in sigmoid_cross_entropy_with_logits
    zeros = array_ops.zeros_like(logits, dtype=logits.dtype)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/array_ops.py", line 1495, in zeros_like
    return gen_array_ops._zeros_like(tensor, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_array_ops.py", line 5960, in _zeros_like
    "ZerosLike", x=x, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 2956, in create_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1470, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

ResourceExhaustedError (see above for traceback): OOM when allocating tensor with shape[16,196416,37]
         [[Node: loss/classification_loss/logistic_loss/zeros_like = ZerosLike[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"](loss/classification_loss/Log)]]
         [[Node: training/Adam/gradients/classification_1/concat_grad/Slice_2/_2985 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:2", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_9615_training/Adam/gradients/classification_1/concat_grad/Slice_2", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:2"]()]]
```

**Comment by hgaiser** [comment]
Although I don't know why it would go OOM after 20 minutes (perhaps due to the evaluation callback?), it does appear that training with batch_size > 1 leads to reduced results. Others and myself have spend some time on figuring out why this is.. but no fix has been found yet. For now my advice is to train with batch_size = 1, and therefore unfortunately no multi-gpu.

**Comment by ChengshuLi** [comment]
@hgaiser Thanks a lot for getting back to me. Just to clarify, when you said "training with batch_size > 1 leads to reduced results", you mean it will have lower accuracy? So to get better training results, I should always use batch_size > 1?

**Comment by hgaiser** [comment]
@ChengshuLi yeah, that's correct. Theoretically larger batch sizes should help, practically there seems to be an issue with how it is implemented. Feel free to debug it :D

**Comment by chrishengbee** [comment]
I have similar issue. For me I am trainning OID dataset, and would encounter OOM trouble evenif I set batch-size = 2. My gpu has ~ 14gb memory.

**Comment by vinitmuchhala** [comment]
I have come across the same issue - in one of the earlier issues there was a discussion that concluded that as long as the batch_size <= num_gpus it will run fine
I tried it out and worked for me

https://github.com/fizyr/keras-retinanet/issues/166

**Comment by ihunhh** [comment]
![image](https://user-images.githubusercontent.com/40879252/59020336-5c74ee00-887c-11e9-9b69-afbafa743cee.png)
