### ISSUE TITLE
Execute script on GPU seems not to work

### ISSUE THREAD

**Issue by remcova** [fizyr/keras-retinanet#744]
I executed the following command to run my script on the GPU but it is very slow. The GPU is not being used, if I do nvidia-smi -l there doesn't appear a new GPU process.
> retinanet-train --freeze-backbone --gpu=0 --weights snapshots/resnet50_coco_best_v2.1.0.h5 csv snapshots/object-detection-crowdai/annotations.csv snapshots/object-detection-crowdai/classes.csv

The GPU I use is a Nvidia Tesla K80 and I installed Tensorflow-gpu and Keras-gpu. 
I use CUDA 9.1 and Cudnn 7.3.1. I did some checks with Tensorflow and it did find the GPU.
So I think this is a problem from keras-retinanet?

**Comment by hgaiser** [comment]
Can you share the output of your train command? Tensorflow should identify the GPU there as well (or print an error if it can't).

**Comment by remcova** [comment]
Thank you for your quick response. Here is my output:
[output.txt](https://github.com/fizyr/keras-retinanet/files/2491338/output.txt)

**Comment by hgaiser** [comment]
It seems like it's not using tensorflow-gpu, but I'm not sure. Could you run:
```python
from tensorflow.python.client import device_lib
print(device_lib.list_local_devices())
```

**Comment by remcova** [comment]
Yeah it only find the CPU:
`
[name: "/device:CPU:0"
device_type: "CPU"
memory_limit: 268435456
locality {
}
incarnation: 1117969152053324859
]
`
How can I fix this? because I did install tensorflow-gpu.

**Comment by remcova** [comment]
Nvm I got it working!
For the people having the same issue, uninstall tensorflow and have only tensorflow-gpu installed in your environment. Make sure you got this piece of code above in your scripts: 

`from tensorflow.python.client import device_lib
print(device_lib.list_local_devices())`

It will detect your GPU and make it available for use.

**Comment by hgaiser** [comment]
Happy to see it works :) and thanks for the feedback.

I do think those lines only print the available devices according to tensorflow, not make them available.

**Comment by remcova** [comment]
Yeah i'm not 100% sure about it but this is what I get from the output.
![image](https://user-images.githubusercontent.com/6126351/47154680-444b6100-d2e3-11e8-803f-d002731d55ee.png)

**Comment by remcova** [comment]
@Humayun-CF 
Do: pip uninstall tensorflow

If you use Anaconda, do: conda uninstall tensorflow --force
The force argument makes sure only the Tensorflow package will be uninstalled, no other dependent packages.
